server:
  port: 16114

spring:
  application:
    name: ts-admin-travel-service

swagger:
  controllerPackage: admintravel.controller

opentracing:
  jaeger:
    udp-sender:
      host: jaeger
      port: 6831
    const-sampler:
      decision: true # 固定采样，全部上报