server:
  port: 16115

spring:
  application:
    name: ts-admin-user-service

swagger:
  controllerPackage: adminuser.controller

opentracing:
  jaeger:
    udp-sender:
      host: jaeger
      port: 6831
    const-sampler:
      decision: true # 固定采样，全部上报