server:
  port: 18767

spring:
  application:
    name: ts-admin-basic-info-service

swagger:
  controllerPackage: adminbasic.microservice

opentracing:
  jaeger:
    udp-sender:
      host: jaeger
      port: 6831
    const-sampler:
      decision: true # 固定采样，全部上报