server:
  port: 15678  # HTTP (Tomcat) port

spring:

  application:
    name: ts-verification-code-service

swagger:
  controllerPackage: verifycode.controller

opentracing:
  jaeger:
    udp-sender:
      host: jaeger
      port: 6831
    const-sampler:
      decision: true # 固定采样，全部上报