spring:
  application:
    name: ts-train-service
  data:
    mongodb:
      host: ts-train-mongo
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: ts
      port: 27017

# HTTP Server
server:
  port: 14567  # HTTP (Tomcat) port

swagger:
  controllerPackage: train.controller

opentracing:
  jaeger:
    udp-sender:
      host: jaeger
      port: 6831
    const-sampler:
      decision: true # 固定采样，全部上报