server:
  port: 18885  # HTTP (Tomcat) port

spring:
  application:
    name: ts-cancel-service

swagger:
  controllerPackage: cancel.controller

opentracing:
  jaeger:
    udp-sender:
      host: jaeger
      port: 6831
    const-sampler:
      decision: true # 固定采样，全部上报