version: '3'
services:

  #  rabbitmq:
  #    image: rabbitmq:management
  #    ports:
  #      - 5672:5672
  #      - 15672:15672
  #    networks:
  #      - trainticket-network

  # kafka:
  #   container_name: kafka
  #   image: spotify/kafka:latest
  #   ports:
  #    - 2181:2181
  #    - 9092:9092
  #   networks:
  #     - trainticket-network

  #  zipkin:
  #    image: openzipkin/zipkin
  #    ports:
  #      - 9411:9411
  #    networks:
  #      - trainticket-network

  redis:
    image: redis
    ports:
      - 6479:6379
    networks:
      - trainticket-network

  ts-ui-dashboard:
    image: codewisdom/ts-ui-dashboard-with-jaeger:v1
    restart: always
    ports:
      - 8080:8080
    networks:
      - trainticket-network

  ts-auth-service:
    image: codewisdom/ts-auth-service-with-jaeger:v1
    restart: always
    ports:
      - 12340:12340
    networks:
      - trainticket-network

  ts-auth-mongo:
    image: mongo:3.4.3
    networks:
      - trainticket-network

  ts-user-service:
    image: codewisdom/ts-user-service-with-jaeger:v1
    restart: always
    ports:
      - 12342:12342
    networks:
      - trainticket-network

  ts-user-mongo:
    image: mongo:3.4.3
    networks:
      - trainticket-network

  ts-verification-code-service:
    image: ts-verification-code-service-with-jaeger:NO_VER
    restart: always
    ports:
      - 15678:15678
    networks:
      - trainticket-network

  ts-account-mongo:
    image: mongo:3.4.3
    networks:
      - trainticket-network

  ts-route-service:
    image: codewisdom/ts-route-service-with-jaeger:v1
    restart: always
    ports:
      - 11178:11178
    networks:
      - trainticket-network

  ts-route-mongo:
    image: mongo:3.4.3
    networks:
      - trainticket-network

  ts-contacts-service:
    image: codewisdom/ts-contacts-service-with-jaeger:v1
    restart: always
    ports:
      - 12347:12347
    networks:
      - trainticket-network

  ts-contacts-mongo:
    image: mongo:3.4.3
    networks:
      - trainticket-network

  ts-order-service:
    image: codewisdom/ts-order-service-with-jaeger:v1
    restart: always
    ports:
      - 12031:12031
    networks:
      - trainticket-network

  ts-order-mongo:
    image: mongo:3.4.3
    networks:
      - trainticket-network

  ts-order-other-service:
    image: codewisdom/ts-order-other-service-with-jaeger:v1
    restart: always
    ports:
      - 12032:12032
    networks:
      - trainticket-network

  ts-order-other-mongo:
    image: mongo:3.4.3
    networks:
      - trainticket-network

  ts-config-service:
    image: codewisdom/ts-config-service-with-jaeger:v1
    restart: always
    ports:
      - 15679:15679
    networks:
      - trainticket-network

  ts-config-mongo:
    image: mongo:3.4.3
    networks:
      - trainticket-network

  ts-station-service:
    image: codewisdom/ts-station-service-with-jaeger:v1
    restart: always
    ports:
      - 12345:12345
    networks:
      - trainticket-network

  ts-station-mongo:
    image: mongo:3.4.3
    networks:
      - trainticket-network

  ts-train-service:
    image: codewisdom/ts-train-service-with-jaeger:v1
    restart: always
    ports:
      - 14567:14567
    networks:
      - trainticket-network

  ts-train-mongo:
    image: mongo:3.4.3
    networks:
      - trainticket-network

  ts-travel-service:
    image: codewisdom/ts-travel-service-with-jaeger:v1
    restart: always
    ports:
      - 12346:12346
    networks:
      - trainticket-network

  ts-travel-mongo:
    image: mongo:3.4.3
    networks:
      - trainticket-network

  ts-travel2-service:
    image: codewisdom/ts-travel2-service-with-jaeger:v1
    restart: always
    ports:
      - 16346:16346
    networks:
      - trainticket-network

  ts-travel2-mongo:
    image: mongo:3.4.3
    networks:
      - trainticket-network

  ts-preserve-service:
    image: codewisdom/ts-preserve-service-with-jaeger:v1
    restart: always
    ports:
      - 14568:14568
    networks:
      - trainticket-network

  ts-preserve-other-service:
    image: codewisdom/ts-preserve-other-service-with-jaeger:v1
    restart: always
    ports:
      - 14569:14569
    networks:
      - trainticket-network

  ts-basic-service:
    image: codewisdom/ts-basic-service-with-jaeger:v1
    restart: always
    ports:
      - 15680:15680
    networks:
      - trainticket-network

  ts-ticketinfo-service:
    image: codewisdom/ts-ticketinfo-service-with-jaeger:v1
    restart: always
    ports:
      - 15681:15681
    networks:
      - trainticket-network

  ts-price-service:
    image: codewisdom/ts-price-service-with-jaeger:v1
    restart: always
    ports:
      - 16579:16579
    networks:
      - trainticket-network

  ts-price-mongo:
    image: mongo:3.4.3
    networks:
      - trainticket-network

  ts-notification-service:
    image: codewisdom/ts-notification-service-with-jaeger:v1
    restart: always
    ports:
      - 17853:17853
    networks:
      - trainticket-network

  ts-security-service:
    image: codewisdom/ts-security-service-with-jaeger:v1
    restart: always
    ports:
      - 11188:11188
    networks:
      - trainticket-network

  ts-security-mongo:
    image: mongo:3.4.3
    networks:
      - trainticket-network

  ts-inside-payment-service:
    image: codewisdom/ts-inside-payment-service-with-jaeger:v1
    restart: always
    ports:
      - 18673:18673
    networks:
      - trainticket-network

  ts-inside-payment-mongo:
    image: mongo:3.4.3
    networks:
      - trainticket-network

  ts-execute-service:
    image: codewisdom/ts-execute-service-with-jaeger:v1
    restart: always
    ports:
      - 12386:12386
    networks:
      - trainticket-network

  ts-payment-service:
    image: codewisdom/ts-payment-service-with-jaeger:v1
    restart: always
    ports:
      - 19001:19001
    networks:
      - trainticket-network

  ts-payment-mongo:
    image: mongo:3.4.3
    networks:
      - trainticket-network

  ts-rebook-service:
    image: codewisdom/ts-rebook-service-with-jaeger:v1
    restart: always
    ports:
      - 18886:18886
    networks:
      - trainticket-network

  ts-rebook-mongo:
    image: mongo:3.4.3
    networks:
      - trainticket-network

  ts-cancel-service:
    image: codewisdom/ts-cancel-service-with-jaeger:v1
    restart: always
    ports:
      - 18885:18885
    networks:
      - trainticket-network

  ts-assurance-service:
    image: codewisdom/ts-assurance-service-with-jaeger:v1
    restart: always
    ports:
      - 18888:18888
    networks:
      - trainticket-network

  ts-assurance-mongo:
    image: mongo:3.4.3
    networks:
      - trainticket-network

  ts-seat-service:
    image: codewisdom/ts-seat-service-with-jaeger:v1
    restart: always
    ports:
      - 18898:18898
    networks:
      - trainticket-network

  ts-travel-plan-service:
    image: codewisdom/ts-travel-plan-service-with-jaeger:v1
    restart: always
    ports:
      - 14322:14322
    networks:
      - trainticket-network

  ts-ticket-office-service:
    image: codewisdom/ts-ticket-office-service-with-jaeger:v1
    restart: always
    ports:
      - 16108:16108
    networks:
      - trainticket-network

  ts-ticket-office-mongo:
    image: mongo:3.4.3
    networks:
      - trainticket-network

  ts-news-service:
    image: codewisdom/ts-news-service-with-jaeger:v1
    restart: always
    ports:
      - 12862:12862
    networks:
      - trainticket-network

  ts-news-mongo:
    image: mongo:3.4.3
    networks:
      - trainticket-network

  ts-voucher-mysql:
    image: mysql
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - trainticket-network

  ts-voucher-service:
    image: codewisdom/ts-voucher-service-with-jaeger:v1
    restart: always
    ports:
      - 16101:16101
    depends_on:
      - ts-voucher-mysql
    volumes:
      - /var/lib/mysql
    networks:
      - trainticket-network

  ts-food-map-service:
    image: codewisdom/ts-food-map-service-with-jaeger:v1
    restart: always
    ports:
      - 18855:18855
    networks:
      - trainticket-network

  ts-food-map-mongo:
    image: mongo:3.4.3
    networks:
      - trainticket-network

  ts-route-plan-service:
    image: codewisdom/ts-route-plan-service-with-jaeger:v1
    restart: always
    ports:
      - 14578:14578
    networks:
      - trainticket-network

  ts-food-service:
    image: codewisdom/ts-food-service-with-jaeger:v1
    restart: always
    ports:
      - 18856:18856
    networks:
      - trainticket-network

  ts-consign-service:
    image: codewisdom/ts-consign-service-with-jaeger:v1
    restart: always
    ports:
      - 16111:16111
    networks:
      - trainticket-network

  ts-consign-mongo:
    image: mongo:3.4.3
    networks:
      - trainticket-network

  ts-consign-price-service:
    image: codewisdom/ts-consign-price-service-with-jaeger:v1
    restart: always
    ports:
      - 16110:16110
    networks:
      - trainticket-network

  ts-consign-price-mongo:
    image: mongo:3.4.3
    networks:
      - trainticket-network

  ts-food-mongo:
    image: mongo:3.4.3
    networks:
      - trainticket-network

  ts-admin-basic-info-service:
    image: codewisdom/ts-admin-basic-info-service-with-jaeger:v1
    restart: always
    ports:
      - 18767:18767
    networks:
      - trainticket-network

  ts-admin-order-service:
    image: codewisdom/ts-admin-order-service-with-jaeger:v1
    restart: always
    ports:
      - 16112:16112
    networks:
      - trainticket-network

  ts-admin-route-service:
    image: codewisdom/ts-admin-route-service-with-jaeger:v1
    restart: always
    ports:
      - 16113:16113
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - trainticket-network

  ts-admin-travel-service:
    image: codewisdom/ts-admin-travel-service-with-jaeger:v1
    restart: always
    ports:
      - 16114:16114
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - trainticket-network

  ts-admin-user-service:
    image: codewisdom/ts-admin-user-service-with-jaeger:v1
    restart: always
    ports:
      - 16115:16115
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - trainticket-network

  jaeger:
    image: jaegertracing/all-in-one:1.15
    ports:
      - 17686:16686
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - trainticket-network

  influx:
    image: tutum/influxdb
    ports:
      - 8083:8083
      - 8086:8086
    volumes:
      - influx:/var/lib/influxdb
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - trainticket-network

  cadvisor:
    image: google/cadvisor
    ports:
      - 8084:8080
    hostname: '{{.Node.Hostname}}'
    command: -logtostderr -docker_only -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_user=root -storage_driver_password=root  -storage_driver_host=influx:8086
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - influx
    deploy:
      mode: global
    networks:
      - trainticket-network

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
    depends_on:
      - influx
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - trainticket-network

  elk:
    image: sebp/elk:630
    ports:
      - 5601:5601 # Kibana web interface
      - 9200:9200 # Elasticsearch JSON interface
      - 5044:5044 # Logstash Beats interface
      - 9300:9300 # Elasticsearch's transport interface
    networks:
      - trainticket-network
  # pilot:
  #   image: registry.cn-hangzhou.aliyuncs.com/acs-sample/log-pilot:latest
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - /:/host
  #   privileged: true
  #   environment:
  #     FLUENTD_OUTPUT: elasticsearch #按照您的需要替换
  #     ELASTICSEARCH_HOST: elk #按照您的需要替换
  #     ELASTICSEARCH_PORT: 9200
  #   networks:
  #     - trainticket-network

networks:
  trainticket-network:
    # driver: overlay
    driver: bridge

volumes:
  influx:
    driver: local
  grafana:
    driver: local
