# HTTP Server
server:
  port: 15681  # HTTP (Tomcat) port

spring:
  application:
    name: ts-ticketinfo-service


swagger:
  controllerPackage: ticketinfo.controller

opentracing:
  jaeger:
    udp-sender:
      host: jaeger
      port: 6831
    const-sampler:
      decision: true # 固定采样，全部上报